<a href="https://colab.research.google.com/github/keerthanaa-babu/EDA-sem-3/blob/main/Exp5(1%262)_04_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv('/content/powerconsumption.csv')

In [18]:
bins = [50,60,70,80,90]

In [19]:
category = pd.cut(df['Humidity'], bins)
category

0        (70, 80]
1        (70, 80]
2        (70, 80]
3        (70, 80]
4        (70, 80]
           ...
52411    (70, 80]
52412    (70, 80]
52413    (70, 80]
52414    (70, 80]
52415    (70, 80]
Name: Humidity, Length: 52416, dtype: category
Categories (4, interval[int64, right]): [(50, 60] < (60, 70] < (70, 80] < (80, 90]]

In [20]:
category.value_counts()

Humidity
(80, 90]    13286
(60, 70]    11729
(70, 80]    11337
(50, 60]     7606
Name: count, dtype: int64

In [21]:
category.head(70)

0     (70, 80]
1     (70, 80]
2     (70, 80]
3     (70, 80]
4     (70, 80]
        ...
65    (60, 70]
66    (60, 70]
67    (60, 70]
68    (50, 60]
69    (50, 60]
Name: Humidity, Length: 70, dtype: category
Categories (4, interval[int64, right]): [(50, 60] < (60, 70] < (70, 80] < (80, 90]]

In [24]:
Humidity_labels=['Low Humidity','Moderate Humidity','High Humidity','Very High Humidity']
df['Humidity_Level']=pd.cut(df['Humidity'],bins,labels=Humidity_labels)
df[['Humidity','Humidity_Level']].tail(30)

       Humidity     Humidity_Level
52386     61.15  Moderate Humidity
52387     61.75  Moderate Humidity
52388     62.22  Moderate Humidity
52389     62.85  Moderate Humidity
52390     63.12  Moderate Humidity
52391     63.35  Moderate Humidity
52392     63.38  Moderate Humidity
52393     63.42  Moderate Humidity
52394     63.62  Moderate Humidity
52395     64.75  Moderate Humidity
52396     64.52  Moderate Humidity
52397     64.25  Moderate Humidity
52398     65.49  Moderate Humidity
52399     69.83  Moderate Humidity
52400     71.70      High Humidity
52401     70.20      High Humidity
52402     71.10      High Humidity
52403     69.73  Moderate Humidity
52404     68.49  Moderate Humidity
52405     70.10      High Humidity
52406     70.10      High Humidity
52407     71.00      High Humidity
52408     71.20      High Humidity
52409     71.00      High Humidity
52410     72.50      High Humidity
52411     72.40      High Humidity
52412     72.60      High Humidity
52413     72.80      High Humidity
52414     73.00      High Humidity
52415     74.10      High Humidity

In [25]:
df['Humidity_Level'].value_counts()

Humidity_Level
Very High Humidity    13286
Moderate Humidity     11729
High Humidity         11337
Low Humidity           7606
Name: count, dtype: int64

In [60]:
df['Humidy_freq']=pd.qcut(df['Humidity'],q=4)
df[['Humidity','Humidy_freq']].tail(30)
df['Humidy_freq'].value_counts()

Humidy_freq
(69.86, 81.4]      13141
(11.339, 58.31]    13121
(58.31, 69.86]     13093
(81.4, 94.8]       13061
Name: count, dtype: int64

In [62]:
df['Humidity_Equal_Width'] = pd.cut(df['Humidity'], bins=4, precision=1)
print(df['Humidity_Equal_Width'].value_counts())

Humidity_Equal_Width
(53.1, 73.9]    22060
(73.9, 94.8]    21365
(32.2, 53.1]     7830
(11.3, 32.2]     1161
Name: count, dtype: int64

In [63]:
pd.cut(np.random.rand(80), 5, precision=2)

[(0.2, 0.39], (0.39, 0.59], (0.59, 0.79], (0.0023, 0.2], (0.0023, 0.2], ..., (0.2, 0.39], (0.39, 0.59], (0.79, 0.98], (0.79, 0.98], (0.2, 0.39]]
Length: 80
Categories (5, interval[float64, right]): [(0.0023, 0.2] < (0.2, 0.39] < (0.39, 0.59] < (0.59, 0.79] <
                                           (0.79, 0.98]]

In [65]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4)
print(category3.value_counts())

(-0.000799, 0.247]    500
(0.247, 0.488]        500
(0.488, 0.75]         500
(0.75, 1.0]           500
Name: count, dtype: int64

In [64]:
mean_val = df['Humidity'].mean()
median_val = df['Humidity'].median()

print(f"Mean:   {mean_val:.2f}")
print(f"Median: {median_val:.2f}")

Mean:   68.26
Median: 69.86

In [39]:
pd.cut([np.random.randint(1,100)], 5, precision=2)

[(66.99, 67.01]]
Categories (5, interval[float64, right]): [(66.93, 66.96] < (66.96, 66.99] < (66.99, 67.01] <
                                           (67.01, 67.04] < (67.04, 67.07]]

In [42]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [53]:
min_max_scaler = MinMaxScaler()

df['Humidity_min_max']=min_max_scaler.fit_transform(df[['Humidity']])

df[['Humidity','Humidity_min_max']].head()

   Humidity  Humidity_min_max
0      73.8          0.748382
1      74.5          0.756770
2      74.5          0.756770
3      75.0          0.762761
4      75.7          0.771148

In [55]:
standard_scaler = StandardScaler()
df['Humidity_Standard']=standard_scaler.fit_transform(df[['Humidity']])

df[['Humidity','Humidity_Standard']].head()

   Humidity  Humidity_Standard
0      73.8           0.356277
1      74.5           0.401291
2      74.5           0.401291
3      75.0           0.433443
4      75.7           0.478456